version: '3.8'
services:
  #WEB
  web:
    build:
      context: .
      dockerfile: Dockerfile
      # target: dev
      args:
        - APP_ENV=${APP_ENV}
    restart: always
    env_file:
      - .env
    command: yarn dev
    # environment:
    #   - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      # - 8086:3000
      - 8018:3000
    container_name: polis-press-web
